default:
  resource:
    path: ../src/Default/Application/Controller/
    namespace: App\Default\Application\Controller
  type: attribute
user:
  resource:
    path: ../src/User/Application/Controller/
    namespace: App\User\Application\Controller
  type: attribute
