user:
  resource:
    path: ../src/User/Application/Controller/
    namespace: App\User\Application\Controller
  type: attribute
api_login_check:
  path: /api/login
  controller: lexik_jwt_authentication.controller::login
  methods: ['POST']
product:
  resource:
    path: ../src/Product/Application/Controller/
    namespace: App\Product\Application\Controller
  type: attribute
  prefix: /api/product
subscription:
  resource:
    path: ../src/Subscription/Application/Controller/
    namespace: App\Subscription\Application\Controller
  type: attribute
  prefix: /api/subscription