default:
  resource:
    path: ../src/Default/Application/Controller/
    namespace: App\Default\Application\Controller
  type: attribute
menu:
  resource:
    path: ../src/Menu/Application/Controller/
    namespace: App\Menu\Application\Controller
  type: attribute
restaurant:
  resource:
    path: ../src/Restaurant/Application/Controller/
    namespace: App\Restaurant\Application\Controller
  type: attribute
search:
  resource:
    path: ../src/Search/Application/Controller/
    namespace: App\Search\Application\Controller
  type: attribute
