default:
    @just -l;

# Build the Docker images
build:
	docker-compose build

init-db:
    docker-compose exec php php bin/console doctrine:database:create

# Start the Docker containers
start:
	docker-compose up -d

# Stop the Docker containers
stop:
	docker-compose down

# Install Composer dependencies
composer-install:
	docker-compose run --rm php composer install --no-plugins

# Update Composer dependencies
composer-update:
	docker-compose run --rm php composer update --no-plugins

# Run Symfony migrations
migrate:
	docker-compose run --rm php bin/console doctrine:migrations:migrate --no-interaction

# Clear Symfony cache
clear-cache:
	docker-compose run --rm php bin/console cache:clear

# Run Symfony tests
run-tests:
	docker-compose run --rm php bin/phpunit --coverage-text

# Access the Symfony container shell
shell:
	docker-compose exec php sh

# Tail the Nginx access logs
nginx-logs:
	docker-compose logs -f nginx

# Tail the Symfony logs
symfony-logs:
	docker-compose exec php tail -f var/log/dev.log
