doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset: utf8mb4
        options:
            "1001": true
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '15'
        mapping_types:
            enum: string
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            email_vo: App\Shared\Infrastructure\Persistence\Doctrine\Type\EmailType
            billing_period: App\Product\Infrastructure\Persistence\Doctrine\Type\BillingPeriodType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Product:
                type: xml
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Product'
                alias: Product
                is_bundle: false
            User:
                type: xml
                dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\User'
                alias: User
                is_bundle: false
        dql:
            numeric_functions:
                uuid: 'Ramsey\Uuid\Doctrine\Functions\UuidFunction'
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
